### ISSUE TITLE
Http.Client: Build fails with tls >= 2.0 — No instance for 'Default TLS.Supported'

### ISSUE THREAD

**Issue by NickSeagull** [neohaskell/NeoHaskell#435]
## Problem

`http/Http/Client.hs` line 324 uses `def` (from `Data.Default`) to construct a `TLS.Supported` value:

```haskell
def {TLS.supportedVersions = secureTlsSupportedVersions}
```

This fails to compile with `tls >= 2.0` because the `Default` instance for `TLS.Supported` was removed when `tls` switched its dependency from `data-default` to `data-default-class`.

### Build error

```
http/Http/Client.hs:324:15: error: [GHC-39999]
    • No instance for 'Default TLS.Supported'
        arising from a use of 'def'
    • In the expression: def
      In a record update at field 'TLS.supportedVersions',
      with type constructor 'TLS.Supported'
      and data constructor 'TLS.Supported'.
      In the expression:
        def {TLS.supportedVersions = secureTlsSupportedVersions}
```

## Suggested fix

Replace `def` with `defaultSupported` from `Network.TLS`:

```haskell
-- Before (line 324)
def {TLS.supportedVersions = secureTlsSupportedVersions}

-- After
TLS.defaultSupported {TLS.supportedVersions = secureTlsSupportedVersions}
```

Similar changes may be needed for any other uses of `def` with TLS types (e.g. `TLS.ClientParams`, `TLS.Shared`) throughout the `http` package.

Ensure the test suite works with the latest env.

## Context

- `tls-2.0.0` (Feb 2024) — major overhaul, removed TLS 1.0/1.1
- `tls-2.1.0` (June 2024) — switched from `data-default` to `data-default-class`, removing all `Default` instances
- `warp-tls` and the broader ecosystem have already migrated to `defaultSupported`
